language: go
go:
  - 1.6
  - 1.7
  - tip
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
script:
  - go test . -v -covermode=count -coverprofile=auth.coverprofile
  - gocovmerge *.coverprofile > merged.coverprofile
  - goveralls -coverprofile=merged.coverprofile -service=travis-ci
matrix:
  allow_failures:
    - go: tip
